---
 - name: deploy wildfly application
   become: yes
   hosts: all
   tasks:
    - name: update ubuntu packages
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
        force_apt_get: true
    - name: Install openjdk-11
      ansible.builtin.apt:
        name: default-jdk
        state: present
